### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by sawmon71293** [dev-mamun/softexpo#2]
[]([]([](https://github.com/dev-mamun/softexpo/blob/bfe261e1b45cce7955b1c1fb97ed9645ed7fe9ea/index.html#L34)))

- Your design is quite unique and beautiful however if you can extend the nav-bar height to the whole view port height for mobile view, your design would be flawless
![peertopeer](https://user-images.githubusercontent.com/102650102/219578998-04c2511f-128c-4b91-9a5d-2769d3fa782c.png)

**Comment by alphym** [comment]
- you did a great job by adding alternate to some of your images but you did not add them to all your images to index.html,I suggest you consider adding alternate to all your images.
