### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by dev-mamun** [dev-mamun/softexpo#3]
Please write your suggestion

**Comment by torobucci** [comment]
Hi @dev-mamun 👋

- ## To Highlight
- Good job on implementing the correct github workflow ✔️ 
- Good job on making your website responsive ✔️  
- Good job on implementing html , css and javascript best practices ✔️
- Great job on making your website more similar to the design and good choice of the topic ✔

## Issues
I would like to suggest a few issues to make your website better

- On the more button, I suggest you change its text content to "less" when clicked. 
  Currently when the more button is clicked the "angle-top icon" disappears and the text content remains the same

![Capture](https://user-images.githubusercontent.com/103370560/220556989-91de1a04-fe9c-4b50-8d91-11c555ae5fa0.PNG)
